### ISSUE TITLE
404 error on "message" from profile

### ISSUE THREAD

**Issue by samiejimmons** [iPaulPro/BitCloutPlus#4]
I'm receiving a 404 error on being redirected to the inbox via the message button, even on accounts I have previously messaged -  seems the new message tabs are the issue, hope you're able to sort it out with the new inbox, was an excellent feature that core devs should have implemented from day 1.

**Comment by iPaulPro** [comment]
Unfortunately it's no longer possible to navigate directly to a message. Hopefully we can get frontend to reinstate this.
